#!/bin/sh
# postinst script for remastersys
#
# see: dh_installdeb(1)

set -e

if [ -f /etc/remastersys.conf.old ]; then
    mv -f /etc/remastersys.conf.old /etc/remastersys.conf
fi

if [ -f /etc/remastersys/splash.png.saved ]; then
    mv -f /etc/remastersys/splash.png.saved /etc/remastersys/splash.png
fi

exit 0
