#!/bin/bash

printf "\n Número da nova versão: "
read version

# Tamanho das pastas
size=$(du -s refisefuqui | cut -f 1)
sizegui=$(du -s refisefuqui-gui | cut -f 1)

# Version
cd refisefuqui/etc/refisefuqui
echo "REFISEFUQUIVERSION=\"$version\"" > refisefuqui.version

# subindo para /refisefuqui
cd ..
cd ..

# Changelog
cd usr/share/doc/refisefuqui

# Dezipa changelog
gzip -d changelog.Debian.gz
rm changelog.gz

# Renomeia changelog
mv changelog.Debian tmp

changelogRead(){
	read changes
	if [ "$changes" != "f" ]; then
		echo "	* "$changes >> tmp2
		echo ""
		cat tmp2
		changelogAsk
	else
		echo "" >> tmp2
		echo " -- Nerun <nerunblogs@gmail.com>  "$(date -R) >> tmp2
		echo "" >> tmp2
	fi
}

changelogAsk(){
	echo ""
	echo " Escreva as Alterações. Digite \"f\" e dê \"enter\" se tiver acabado."
	changelogRead
}

echo "refisefuqui ($version) stable; urgency=low" > tmp2
echo "" >> tmp2
changelogAsk
cat tmp2 > changelog.Debian
cat tmp >> changelog.Debian
rm tmp2
rm tmp

gzip -k changelog.Debian
cp changelog.Debian.gz changelog.gz
rm changelog.Debian

# subindo para /refisefuqui
cd ..
cd ..
cd ..
cd ..

# md5sum
find . -type d -name "DEBIAN" -prune -o -type f -printf '%P ' | xargs md5sum > ./DEBIAN/md5sums

# DEBIAN/CONTROL

md5faz(){
	md5sum $1 | cut -f 1 -d " "
}

a=$(md5faz ./etc/refisefuqui/refisefuqui.version)
b=$(md5faz ./etc/refisefuqui/preseed/custom.seed)
c=$(md5faz ./etc/refisefuqui/isolinux/vesamenu.c32)
d=$(md5faz ./etc/refisefuqui/isolinux/stdmenu.cfg)
e=$(md5faz ./etc/refisefuqui/isolinux/isolinux.cfg)
f=$(md5faz ./etc/refisefuqui/isolinux/menu.cfg)
g=$(md5faz ./etc/refisefuqui/isolinux/isolinux.bin)
h=$(md5faz ./etc/refisefuqui/isolinux/live.cfg)
i=$(md5faz ./etc/refisefuqui/isolinux/memtest.bin)
j=$(md5faz ./etc/refisefuqui/isolinux/splash.png)
k=$(md5faz ./etc/refisefuqui/refisefuqui-installer.conf)
l=$(md5faz ./etc/refisefuqui.conf)

cd DEBIAN

echo "Package: refisefuqui
Priority: optional
Section: system
Installed-Size: $size
Maintainer: Nerun <nerunblogs@gmail.com>
Architecture: all
Version: $version
Depends: coreutils, dialog, memtest86+, mkisofs | genisoimage, findutils, grub-pc, syslinux | xorriso, os-prober, bash, passwd, sed, squashfs-tools, live-boot, live-config, live-config-sysvinit | live-config-systemd, live-boot-initramfs-tools, rsync, mount, laptop-detect, util-linux, hwdata
Conffiles:
 /etc/refisefuqui/refisefuqui.version $a
 /etc/refisefuqui/preseed/custom.seed $b
 /etc/refisefuqui/isolinux/vesamenu.c32 $c
 /etc/refisefuqui/isolinux/stdmenu.cfg $d
 /etc/refisefuqui/isolinux/isolinux.cfg $e
 /etc/refisefuqui/isolinux/menu.cfg $f
 /etc/refisefuqui/isolinux/isolinux.bin $g
 /etc/refisefuqui/isolinux/live.cfg $h
 /etc/refisefuqui/isolinux/memtest.bin $i
 /etc/refisefuqui/isolinux/splash.png $j
 /etc/refisefuqui/refisefuqui-installer.conf $k
 /etc/refisefuqui.conf $l
Description: Remasteriza e cria backups do sistema Debian
 O ReFiSeFuQui permite criar uma Distribuição em Live CD ou fazer um backup do sistema instalado em sua máquina.
 Para mais informações visite http://linuxernoob.blogspot.com.br" > control

# subindo pra /remastersys
cd ..
cd ..

# REFISEFUQUI-GUI

# descendo para GUI
cd refisefuqui-gui

# MD5SUM
find . -type d -name "DEBIAN" -prune -o -type f -printf '%P ' | xargs md5sum > ./DEBIAN/md5sums

cd DEBIAN

# DEBIAN/CONTROL

echo "Package: refisefuqui-gui
Priority: optional
Section: system
Installed-Size: $size
Maintainer: Nerun <nerunblogs@gmail.com>
Architecture: all
Version: $version
Depends: gparted, xterm, yad, read-edid, gksu, refisefuqui (>= $version)
Description: Remasteriza e cria backups do sistema Debian
 Esta é a interface visual do Refisefuqui.
 Para mais informações visite http://linuxernoob.blogspot.com.br" > control

# EMPACOTAMENTO

# subindo pra /remastersys
cd ..
cd ..

# Renomar pasta refisefuqui para empacotamento
nome="refisefuqui_"$version"_all"
nomegui="refisefuqui-gui_"$version"_all"

mv refisefuqui $nome
mv refisefuqui-gui $nomegui

# Empacotando
dpkg -b $nome
dpkg -b $nomegui

# Desnomear pasta após empacotamento
mv $nome refisefuqui
mv $nomegui refisefuqui-gui
