#!/bin/bash

printf "\n New version number: "
read version

author="Daniel Dias Rodrigues <danieldiasr@gmail.com>"
url="https://github.com/nerun/remastersys"

# ==============================================================================
# REMASTERSYS ==================================================================
# ==============================================================================

# UPDATE VERSION
echo "VERSION=\"$version\"" > ./remastersys/etc/remastersys/remastersys.version

# MANPAGES PREPARATION
gzip remastersys/usr/share/man/man1/remastersys.1

# CHANGELOG UPDATE
cd remastersys/usr/share/doc/remastersys
mv changelog changelog.old

changelogRead(){
	read changes
	if [ "$changes" != "f" ]; then
		echo "	* "$changes >> changelog
		echo ""
		cat changelog
		changelogAsk
	else
		echo "" >> changelog
		echo " -- $author  "$(date -R) >> changelog
		echo "" >> changelog
	fi
}

changelogAsk(){
	echo ""
	echo " Write changes, then write \"f\" in a new line and press \"ENTER\" when finished."
	changelogRead
}

echo "remastersys ($version) stable; urgency=low" > changelog
echo "" >> changelog
changelogAsk
cat changelog.old >> changelog
rm changelog.old

# Creating changelog.gz and changelog.Debian.gz
cp changelog changelog.Debian
gzip changelog
gzip changelog.Debian

# MOVING LOCALES .po AND .POT
cd ../..
cd ./locale/pt_BR/LC_MESSAGES
# /remastersys/remastersys/usr/share/locale/pt_BR/LC_MESSAGES
mv *.po ../../../../../..
mv *.pot ../../../../../..

# DEBIAN/CONTROL UPDATE

# Move up to ./remastersys
cd ../../../../..

# md5sum
find . -type d -name "DEBIAN" -prune -o -type f -printf '%P ' | xargs md5sum > ./DEBIAN/md5sums

md5run(){
	md5sum $1 | cut -f 1 -d " "
}

a=$(md5run ./etc/remastersys.conf)
b=$(md5run ./etc/remastersys/isolinux/isolinux.bin)
c=$(md5run ./etc/remastersys/isolinux/isolinux.cfg)
d=$(md5run ./etc/remastersys/isolinux/ldlinux.c32)
e=$(md5run ./etc/remastersys/isolinux/libcom32.c32)
f=$(md5run ./etc/remastersys/isolinux/libutil.c32)
g=$(md5run ./etc/remastersys/isolinux/memtest86.bin)
h=$(md5run ./etc/remastersys/isolinux/splash-default.png)
i=$(md5run ./etc/remastersys/isolinux/splash.png)
j=$(md5run ./etc/remastersys/isolinux/vesamenu.c32)
k=$(md5run ./etc/remastersys/preseed/custom.seed)
l=$(md5run ./etc/remastersys/remastersys-installer.conf)
m=$(md5run ./etc/remastersys/remastersys.version)


# Move down to ./remastersys/DEBIAN
cd DEBIAN

# Calculate folder size
size=$(du -s ../../remastersys | cut -f 1)

echo "Package: remastersys
Priority: optional
Section: system
Installed-Size: $size
Maintainer: $author
Architecture: all
Version: $version
Depends: awk, bash, coreutils, dialog, fdisk, findutils, grub-pc, hwdata, laptop-detect, live-boot-initramfs-tools, live-boot, live-config-sysvinit | live-config-systemd, live-config, memtest86+, mkisofs | genisoimage, mount, os-prober, passwd, rsync, sed, squashfs-tools, sudo, syslinux | xorriso, syslinux-utils, util-linux
Conffiles:
 /etc/remastersys.conf $a
 /etc/remastersys/isolinux/isolinux.bin $b
 /etc/remastersys/isolinux/isolinux.cfg $c
 /etc/remastersys/isolinux/ldlinux.c32 $d
 /etc/remastersys/isolinux/libcom32.c32 $e
 /etc/remastersys/isolinux/libutil.c32 $f
 /etc/remastersys/isolinux/memtest86.bin $g
 /etc/remastersys/isolinux/splash.png $h
 /etc/remastersys/isolinux/splash-default.png $i
 /etc/remastersys/isolinux/vesamenu.c32 $j
 /etc/remastersys/preseed/custom.seed $k
 /etc/remastersys/remastersys-installer.conf $l
 /etc/remastersys/remastersys.version $m
Homepage: $url
Description: Remaster and create backups of the Debian system
 Remastersys allows you to create a Live CD/DVD distribution or make a backup
 of the system installed on your machine." > control

# Get back to Remastersys GitHub root folder
cd ../..

# ==============================================================================
# REMASTERSYS-GUI ==============================================================
# ==============================================================================

# down to GUI
cd remastersys-gui

# md5sum
find . -type d -name "DEBIAN" -prune -o -type f -printf '%P ' | xargs md5sum > ./DEBIAN/md5sums

# Move down to ./remastersys-gui/DEBIAN
cd DEBIAN

# DEBIAN/CONTROL

# Calculate folder size
sizegui=$(du -s ../../remastersys-gui | cut -f 1)

echo "Package: remastersys-gui
Priority: optional
Section: system
Installed-Size: $sizegui
Maintainer: $author
Architecture: all
Version: $version
Depends: gparted, read-edid, remastersys (>= $version), xterm, yad
Homepage: $url
Description: Remaster and create backups of the Debian system
 This is the visual interface of Remastersys." > control

# Get back to Remastersys GitHub root folder
cd ../..

# ==============================================================================
# PACKAGING ====================================================================
# ==============================================================================

# Permissions
#sudo chmod -R 755 remastersys
#sudo chmod -R 755 remastersys-gui
#sudo chmod -x remastersys-gui/usr/share/menu/remastersys

# Rename remastersys folder for packaging
name="remastersys_"$version"_all"
namegui="remastersys-gui_"$version"_all"

mv remastersys $name
mv remastersys-gui $namegui

# Packaging
dpkg-deb -b --root-owner-group $name
dpkg-deb -b --root-owner-group $namegui

# ==============================================================================
# RESTORATION ==================================================================
# ==============================================================================

# folders names
mv $name remastersys
mv $namegui remastersys-gui

# delete gziped changelogs and restore single textual changelog
rm ./remastersys/usr/share/doc/remastersys/changelog.Debian.gz
gzip -d ./remastersys/usr/share/doc/remastersys/changelog.gz

# manpages restoration
gzip -d ./remastersys/usr/share/man/man1/remastersys.1.gz

# .po and .pot restoration
mv *.po ./remastersys/usr/share/locale/pt_BR/LC_MESSAGES
mv *.pot ./remastersys/usr/share/locale/pt_BR/LC_MESSAGES
