#!/bin/bash

# refisefuqui-gui script to make an installable livecd/dvd from a Debian installed 
# and customized system
#
#  ReFiSeFuQui created by "Nerun"
#  Copyright 2013-2014 Under the GNU GPL2 License
#
#  Fork of Remastersys, created by Tony "Fragadelic" Brijeski
#
#  Remastersys:
#  Copyright 2007-2012 Under the GNU GPL2 License
#  Created October 28th, 2007,2008
#  Updated July 2012

#  This script requires yad to run

testroot="`whoami`"

#if [ "$testroot" != "root" ]; then
#$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"Deve ser executado com privilégios de superusuário."
#exit 1
#fi

testzenity=`which zenity`

if [ "$testzenity" = "" ]; then
	apt-get -y -q install zenity
fi

mainmenu () {

	if [ "$testzenity" != "" ]; then
		OUT=$(zenity --list --width=810 --height=368 \
		  --title="Criador de ReFiSeFuQui" \
		  --column="Opções" --column="Descrição" \
			Backup "Backup completo do sistema incluindo arquivos do usuário" \
			Dist "Criar 'distribuição' em Live CD/DVD. Cria CDFS (sistema de arquivos de CD) e ISO (imagem gravável de CD)" \
			DistCDFS "Criar somente o CDFS de um Live CD/DVD - ideal, se você deseja adicionar arquivos ao CD" \
			DistISO "Criar somente a ISO de um Live CD/DVD - o CDFS deve ter sido criado anteriormente" \
			DistBoot "Selecionar imagem de fundo para o menu de inicialização do Live CD/DVD" \
			DistGrub "Selecionar imagem de fundo para o carregador de inicialização GRUB" \
			DistSkel "Tornar as configurações personalizadas do usuário atual em padrões do sistema do Live CD/DVD" \
			Configurar "Modificar as configurações do ReFiSeFuQui" \
			Limpar "Limpar a pasta de trabalho do ReFiSeFuQui" \
			LimparSkel "Limpar as configurações de /etc/skel para remover todas as personalizações" \
			Log "Visualizar o arquivo de log do ReFiSeFuQui" \
			Sobre "Sobre o Criador de ReFiSeFuQui")
		escolha $OUT
	fi
}

escolha () {

	arg1=$1

	if [ "$arg1" = "" ]; then
		zenity --info \
			--text="Nenhuma opção selecionada.\n\nSaindo do ReFiSeFuQui..."
	elif [ "$arg1" = Backup ]; then
		backupmenu
	elif [ "$arg1" = Dist ]; then
		distmenu
	elif [ "$arg1" = DistCDFS ]; then
		distcdfsmenu
	elif [ "$arg1" = DistISO ]; then
		distisomenu
	elif [ "$arg1" = DistBoot ]; then
		distbootmenu
	elif [ "$arg1" = DistGrub ]; then
		distgrubmenu
	elif [ "$arg1" = DistSkel ]; then
		distskelmenu
	elif [ "$arg1" = Configurar ]; then
		modifymenu
	elif [ "$arg1" = Limpar ]; then
		cleanmenu
	elif [ "$arg1" = LimparSkel ]; then
		find /etc/skel/ -type f -exec rm -f '{}' \;
		zenity --info \
			--text="Os arquivos de configuração em /etc/skel/ foram apagados."
		mainmenu
	elif [ "$arg1" = Log ]; then
		. /etc/refisefuqui.conf
		if [ -f "$WORKDIR/refisefuqui/refisefuqui.log" ]; then
			zenity --text-info --width=750 --height=400 \
				--title="Arquivo de Log" \
				--filename="$WORKDIR/refisefuqui/refisefuqui.log"
		else
			zenity --info \
				--title="Log não encontrado" \
				--text="O arquivo refisefuqui.log não existe."
		fi
		mainmenu
	elif [ "$arg1" = Sobre ]; then
		. /etc/refisefuqui/refisefuqui.version
		zenity --info --title="Sobre o ReFiSeFuQui" \
			--text="O Criador de ReFiSeFuQui é uma interface visual para o
refisefuqui: uma ferramenta em linha de comando que
transforma um sistema Debian instalado (ou derivado) em
uma distribuição em Live CD ou DVD. Podendo ser usado
também como uma ferramenta de backup completo (incluindo
a pasta /home e todos os dados de usuários).

Esta é a versão $REFISEFUQUIVERSION.

Criador de ReFiSeFuQui por Daniel 'Nerun' Rodrigues.

Fork do Remastersys, de Tony Brijeski (descontinuado).

Visite http://linuxernoob.blogspot.com.br/ para obter
mais informações."
		mainmenu
	else
		exit 0
	fi

}

backupmenu () {

	zenity --info --title="Modo Backup" \
		--text="Você escolheu o Modo de Backup.

Não interrompa este processo.

Clique em OK para iniciar o processo de criação do LiveCD/DVD de Backup."

	xterm -fn 9x15 -e "refisefuqui backup"

	. /etc/refisefuqui.conf

	SQUASHFSSIZE=`ls -s $WORKDIR/refisefuqui/ISOTMP/live/filesystem.squashfs | awk -F " " '{print $1}'`

	if [ "$SQUASHFSSIZE" -gt "3999999" ]; then
		zenity --info --title="Falha" \
			--text="O sistema de arquivos comprimido é maior do
que permite a especificação iso9660 para um
único arquivo.

Você deve tentar reduzir a quantidade de
arquivos e tentar novamente."
		exit 1
	fi

	zenity --info --title="Backup finalizado" \
		--text="Seus arquivos $CUSTOMISO e $CUSTOMISO.md5 estão prontos
em $WORKDIR/refisefuqui.

É recomendável testá-los em uma máquina virtual ou em um
CD/DVD regravável para se certificar que ele funciona
conforme desejado.

Clique em OK para retornar ao menu principal."

	mainmenu

}

distmenu () {

	zenity --info --title="Modo Dist" \
		--text="Você escolheu o Modo Dist.

Clique em OK para iniciar o processo de
criação da Distribuição Live CD/DVD."

	xterm -fn 9x15 -e "refisefuqui dist"

	. /etc/refisefuqui.conf

	SQUASHFSSIZE=`ls -s $WORKDIR/refisefuqui/ISOTMP/live/filesystem.squashfs | awk -F " " '{print $1}'`

	if [ "$SQUASHFSSIZE" -gt "3999999" ]; then
		zenity --info --title="Falha" \
			--text="O sistema de arquivos comprimido é maior do
que permite a especificação iso9660 para um
único arquivo.

Você deve tentar reduzir a quantidade de
arquivos e tentar novamente."
		exit 1
	fi

	zenity --info --title="Dist finalizado" \
		--text="Seus arquivos $CUSTOMISO e $CUSTOMISO.md5 estão prontos
em $WORKDIR/refisefuqui.

É recomendável testá-los em uma máquina virtual ou em um
CD/DVD regravável para se certificar que ele funciona
conforme desejado.

Clique em OK para retornar ao menu principal."

	mainmenu

}

distcdfsmenu () {

	zenity --info --title="Modo Dist CDFS" \
		--text="Você escolheu o Modo Dist CDFS.

Clique em OK para iniciar o processo de
criação do sistema de arquivos da
Distribuição LiveCD/DVD."

	xterm -fn 9x15 -e "refisefuqui dist cdfs"

	. /etc/refisefuqui.conf

	SQUASHFSSIZE=`ls -s $WORKDIR/refisefuqui/ISOTMP/live/filesystem.squashfs | awk -F " " '{print $1}'`

	if [ "$SQUASHFSSIZE" -gt "3999999" ]; then
		zenity --info --title="Falha" \
			--text="O sistema de arquivos comprimido é maior do
que permite a especificação iso9660 para um
único arquivo.

Você deve tentar reduzir a quantidade de
arquivos e tentar novamente."
		exit 1
	fi

	zenity --info --title="DistCDFS finalizado" \
		--text="Seu sistema de arquivos do Live CD/DVD está pronto em
$WORKDIR/refisefuqui.

Você pode agora adicionar arquivos ao CD e então
executar a opção DistISO quando você estiver pronto.

Clique em OK para retornar ao menu principal."

	mainmenu

}

distisomenu () {

	. /etc/refisefuqui.conf

	if [ -f "$WORKDIR/refisefuqui/ISOTMP/live/filesystem.squashfs" ]; then
		zenity --info --title="Modo DistISO" \
			--text="Você escolheu o Modo DistISO.

Clique em OK para criar o arquivo ISO."

		xterm -fn 9x15 -e "refisefuqui dist iso"

		. /etc/refisefuqui.conf

		SQUASHFSSIZE=`ls -s $WORKDIR/refisefuqui/ISOTMP/live/filesystem.squashfs | awk -F " " '{print $1}'`

		if [ "$SQUASHFSSIZE" -gt "3999999" ]; then
			zenity --info --title="Falha" \
				--text="O sistema de arquivos comprimido é maior do
que permite a especificação iso9660 para um
único arquivo.

Você deve tentar reduzir a quantidade de
arquivos e tentar novamente."
			exit 1
		fi

		zenity --info --title="DistISO finalizado" \
			--text="Seus arquivos $CUSTOMISO e $CUSTOMISO.md5 estão prontos
em $WORKDIR/refisefuqui.

É recomendável testá-los em uma máquina virtual ou em um
CD/DVD regravável para se certificar que ele funciona
conforme desejado.

Clique em OK para retornar ao menu principal."

		mainmenu

	else

		zenity --info --title="Falha" \
			--text="O sistema de arquivos do Live CD/DVD não existe.

Clique OK para voltar ao menu principal e
tentar o Modo Dist ou o Modo DistCDFS novamente."

		mainmenu

	fi

}

distbootmenu () {

	zenity --info --title="Modo DistBoot" \
		--text="
Isto lhe permitirá escolher sua própria figura para ser
a imagem de fundo do menu do Live CD/DVD.

A imagem DEVE ter 640x480 pixels e estar em formato PNG.
Você deve criar esta imagem ou redimensioná-la com um
editor gráfico apropriado, uma vez que esta ferramenta
não possui a habilidade de fazê-lo.

Clique em OK para continuar."

# ---------------------------------------------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------------------------------------------
# --------------- PAREI A CONVERSÃO PARA ZENIT BEM AQUI ---------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------------------------------------------

	BOOTPIC=`$DIALOG $TITLE"Criador de ReFiSeFuQui" --width=750 --height=400 $FILESELECTION`

	if [ "$BOOTPIC" != "" ]; then
		mv /etc/refisefuqui/isolinux/splash.png \
		/etc/refisefuqui/isolinux/splash.png.`date +%F%T | sed -e "s/-//g" | sed -e "s/://g"`

		cp $BOOTPIC /etc/refisefuqui/isolinux/splash.png

		$DIALOG $TITLE"Criador de ReFiSeFuQui" $MSGBOX $TEXT"$BOOTPIC foi copiado \
para \n/etc/refisefuqui/isolinux/splash.png se tornando \na imagem de fundo padrão \
para o menu do Live CD/DVD. \nClique em OK para continuar."

	else
		$DIALOG $TITLE"Criador de ReFiSeFuQui" $MSGBOX $TEXT"Você não selecionou qualquer arquivo. \n\nClique em OK para continuar."
	fi

	mainmenu

}

distgrubmenu () {
$DIALOG $TITLE"Criador de ReFiSeFuQui" $MSGBOX $TEXT"Isto lhe permitirá escolher \
sua própria imagem PNG \ncomo imagem de fundo para o gerenciador de boot GRUB. \
Clique em OK para continuar."

GRUBPIC=`$DIALOG $TITLE"Criador de ReFiSeFuQui" --width=750 --height=400 $FILESELECTION`
if [ "$GRUBPIC" != "" ]; then


$DIALOG $TITLE"Criador de ReFiSeFuQui" $MSGBOX $TEXT"$GRUBPIC foi copiado \
para /etc/refisefuqui/grub.png \ne é a imagem de fundo padrão para o GRUB. \nClique \
OK para atualizar o GRUB com as novas configurações \npara poder ver a imagem na próxima inicialização."
if [ "$?" = "0" ]; then

$DIALOG $TITLE"Criador de ReFiSeFuQui" --no-buttons --progress --pulsate $TEXT"Atualizando GRUB agora. \n\
Por favor aguarde." &
PICFILE=`echo $GRUBPIC | awk -F"/" '{print $NF}'`
cp $GRUBPIC /etc/refisefuqui/grub.png
NEWGRUBPIC="/etc/refisefuqui/grub.png"

sed -i -e "/GRUB_BACKGROUND/d" /etc/default/grub

cat >> /etc/default/grub <<FOO
#Grub Background
GRUB_BACKGROUND="$NEWGRUBPIC"

FOO


update-grub
killall -KILL yad

$DIALOG $TITLE"Criador de ReFiSeFuQui" $MSGBOX $TEXT"GRUB foi atualizado. Clique em OK para continuar."
fi
else

$DIALOG $TITLE"Criador de ReFiSeFuQui" $MSGBOX $TEXT"Você não selecionou qualquer arquivo. \n\nClique em OK para continuar."
fi
mainmenu
}

distskelmenu () {

$DIALOG $TITLE"Criador de ReFiSeFuQui" $MSGBOX $TEXT"Isto colocará a área de trabalho de seu usuário e as configurações de aplicativos \n\
em /etc/skel tornando-os o padrão para o sistema do Live CD/DVD. \n\n\
Incluem-se papel de parede e outras configurações de aplicativos que não estão \n\
definidas na pasta home do usuário. \n\
É preciso compilar uma lista dos usuários válidos. Pode levar alguns minutos para \n\
concluir, então seja paciente. \n\n\
Clique em OK para preparar a lista."


j="0"
i="1000"
while [ "`cat /etc/passwd | awk -F ":" '{print $3}' | grep $i`" != "" ]; do
for i in $(seq 1000 1 1010); do

if [ "`cat /etc/passwd | awk -F ":" '{print $3}' | grep $i`" != "" ]; then
  userchoice[$j]="`grep $i /etc/passwd | awk -F ":" '{print $1}'`"
  
  j=`expr $j + 1`
fi

done
done


SKELUSER=`$DIALOG $TITLE"$TITLETEXT" $MENU $TEXT"\nSelecione um usuário cujas configurações \nvocê deseja tornar padrões." \
${userchoice[0]} ${userchoice[0]} \
${userchoice[1]} ${userchoice[1]} \
${userchoice[2]} ${userchoice[2]} \
${userchoice[3]} ${userchoice[3]} \
${userchoice[4]} ${userchoice[4]} \
${userchoice[5]} ${userchoice[5]} \
${userchoice[6]} ${userchoice[6]} \
${userchoice[7]} ${userchoice[7]} \
${userchoice[8]} ${userchoice[8]} \
${userchoice[9]} ${userchoice[9]}`



SKELUSER=`echo $SKELUSER | cut -d "|" -f 1`

if [ "$SKELUSER" != "" ]; then

cd `grep "^$SKELUSER:" /etc/passwd | awk -F ":" '{print $6}'`

PWD=`pwd`

TESTUSER=`grep "$PWD" /etc/passwd | awk -F ":" '{print $1}'`

if [ "$TESTUSER" != "$SKELUSER" ]; then
$DIALOG $TITLE"Criador de ReFiSeFuQui" $MSGBOX $TEXT"O usuário escolhido não possui um diretório home. \nClique em OK para retornar ao menu principal."
echo "É preciso estar no diretório de usuário... Saindo."
mainmenu
fi


$DIALOG $TITLE"Criador de ReFiSeFuQui" --no-buttons --progress --pulsate $TEXT"Copiando as configurações de $SKELUSER para /etc/skel agora. \n\
Por favor aguarde." &

refisefuqui-skelcopy $SKELUSER

killall -KILL yad

$DIALOG $TITLE"Criador de ReFiSeFuQui" $MSGBOX $TEXT"
As configurações de $SKELUSER foram copiadas para /etc/skel. Para\n\
testá-las você precisa criar um novo usuário e ver se suas \n\
configurações foram aplicadas. \n\n\
Clique em OK para retornar ao menu principal."

else

$DIALOG $TITLE"Criador de ReFiSeFuQui" $MSGBOX $TEXT"Você não selecionou qualquer usuário. \n\nClique em OK para continuar."

fi
mainmenu

}

modifymenu () {

if [ -f /etc/refisefuqui.conf ]; then
. /etc/refisefuqui.conf
fi

if [ "$SQUASHFSOPTS" = "" ]; then
SQUASHFSOPTS="-no-recovery -always-use-fragments -b 1M"
fi


CHOICES=`$DIALOGMENU $TITLE"$TITLETEXT" --button=Salvar:0 --button=Voltar:1 --form \
--field="Nome de usuário do Live CD/DVD" "$LIVEUSER" \
--field="Nome do Sistema do Live CD/DVD" "$LIVECDLABEL" \
--field="Nome da ISO do Live CD/DVD" "$CUSTOMISO" \
--field="Inicialização com GRUB ou com ISOLINUX" "$ISOBOOT" \
--field="Pasta de trabalho do ReFiSeFuQui" "$WORKDIR" \
--field="Opções para mksquashfs" " $SQUASHFSOPTS" \
--field="Exibir ícone de instalação na área de trabalho" "$SHOWICON" \
--field="Arquivos e pastas não inclusos" " $EXCLUDES"`


if [ "$?" = "0" ]; then
LIVEUSER=`echo $CHOICES | cut -d "|" -f 1`
LIVECDLABEL=`echo $CHOICES | cut -d "|" -f 2`
CUSTOMISO=`echo $CHOICES | cut -d "|" -f 3`
ISOBOOT=`echo $CHOICES | cut -d "|" -f 4`
WORKDIR=`echo $CHOICES | cut -d "|" -f 5`
SQUASHFSOPTS=`echo $CHOICES | cut -d "|" -f 6`
SHOWICON=`echo $CHOICES | cut -d "|" -f 7`
EXCLUDES=`echo $CHOICES | cut -d "|" -f 8`
else 
mainmenu
fi

if [ "$LIVEUSER" = "" ]; then
LIVEUSER="live"
fi
#make sure live user is all lowercase
LIVEUSER="`echo $LIVEUSER | awk '{print tolower ($0)}'`"

if [ "$LIVECDLABEL" = "" ]; then
LIVECDLABEL="Custom Live CD"
fi

if [ "$CUSTOMISO" = "" ]; then
CUSTOMISO="custom-live.iso"
fi

if [ "$ISOBOOT" = "grub" -o "$ISOBOOT" = "GRUB" ]; then
ISOBOOT="GRUB"
else
ISOBOOT="ISOLINUX"
fi


if [ "$WORKDIR" = "" ]; then
WORKDIR="/home/refisefuqui"
fi

if [ "$SQUASHFSOPTS" = "" ]; then
SQUASHFSOPTS="-no-recovery -always-use-fragments -b 1M"
fi

SHOWICON="`echo $SHOWICON | awk '{print tolower ($0)}'`"

if [ "$SHOWICON" = "1" ]; then
SHOWICON="1"
elif [ "$SHOWICON" = "yes" ]; then
SHOWICON="1"
elif [ "$SHOWICON" = "true" ]; then
SHOWICON="1"
else
SHOWICON="0"
fi


cat > /etc/refisefuqui.conf <<FOO
#Remastersys Global Configuration File

# This is the temporary working directory and won't be included on the cd/dvd
WORKDIR="$WORKDIR"

# Here you can add any other files or directories to be excluded from the live filesystem
# Separate each entry with a space
EXCLUDES="$EXCLUDES"

# Here you can change the livecd/dvd username
LIVEUSER="$LIVEUSER"

# Here you can change the name of the livecd/dvd label
LIVECDLABEL="$LIVECDLABEL"

# Here you can change the name of the ISO file that is created
CUSTOMISO="$CUSTOMISO"

# Here you can change the boot method for the live - GRUB or ISOLINUX
ISOBOOT="$ISOBOOT"

# Options for mksquashfs
#Default is -no-recovery -always-use-fragments -b 1M
SQUASHFSOPTS="$SQUASHFSOPTS"

#Option to show install icon on live desktop in dist mode 1=yes or true, 0=no or false
SHOWICON="$SHOWICON"


FOO

if [ "$?" = "0" ]; then
$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"Configuração salva. Clique em OK para retornar ao menu de modificação."
else
$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"Erro ao salvar Configuração. Clique em OK para retornar ao menu de modificação."
fi
modifymenu

}

cleanmenu () {
$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"Todos os arquivos da pasta temporária serão apagados.\n\nClique em OK para continuar."
xterm -fn 9x15 -e "refisefuqui clean"
$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"Completado. Clique em OK para retornar ao menu principal."
mainmenu

}

mainmenu
